### PR TITLE
fix(core): Add NanoTDF KID padding removal and update logging level

### LINKED ISSUE #1467: NanoTDF KID padding rewrap fix
Different SDKs implement NanoTDF KID differently - make KAS rewrap more robust - trim from and back if not to spec for 2, 8, 32 bytes

### PR DESCRIPTION
**Pull request by pflynn-virtru**
Introduced padding removal logic in the `GetIdentifier` method of `ResourceLocator` to ensure cleaned identifiers. Also changed log level from Info to Debug in `nanoTDFRewrap` for more appropriate logging detail.

resolves #1467

### CODE REVIEW

File: sdk/resource_locator.go [hunk 1]
```diff
@@ -159,7 +160,10 @@ func (rl ResourceLocator) GetIdentifier() (string, error) {
 		if rl.identifier == "" {
 			return "", fmt.Errorf("no resource locator identifer: %d", rl.protocol)
 		}
-		return rl.identifier, nil
+		// remove padding
+		cleanedIdentifier := strings.TrimRight(rl.identifier, "\x00")
+		cleanedIdentifier = strings.TrimLeft(cleanedIdentifier, "\x00")
```
Comment (dmihalcik-virtru) [inline sdk/resource_locator.go:165]: We should probably decide if we want to pad left or right and just do one, but I'm fine with this for now.

**Review by dmihalcik-virtru — APPROVED** [review]

File: sdk/resource_locator.go (hunk 1 above)
Comment (pflynn-virtru) [reply sdk/resource_locator.go:165]: agreed.  rewrap is more robust (within reason and with security considerations) and the SDK should be more strict and uniform
