### PR TITLE
fix(sdk): conditionally set client_id based on auth method

### LINKED ISSUE #3076: SDK client credentials auth fails when using Okta OAuth provider

### PR DESCRIPTION
**Pull request by imdominicreed**
Move client_id setting from generic request setup to auth-method-specific handlers. This ensures client_id is only included when using client assertion authentication, not for all request types.

### Proposed Changes

* fix #3076 

### Checklist

- [ ] I have added or updated unit tests
- [ ] I have added or updated integration tests (if appropriate)
- [ ] I have added or updated documentation

### CODE REVIEW

File: sdk/auth/oauth/oauth.go [hunk 1]
```diff
@@ -293,8 +293,7 @@ func getTokenExchangeRequest(ctx context.Context, tokenEndpoint, dpopNonce strin
 		data.Set("scopes", strings.Join(scopes, " "))
```
Comment (jentfoo) [inline sdk/auth/oauth/oauth.go]: This line is incorrectly setting the field `scopes` (verified `scope` as used on line 75 is correct: https://www.rfc-editor.org/rfc/rfc8693.html#name-scope-scopes-claim )

Comment (imdominicreed) [reply sdk/auth/oauth/oauth.go]: good catch!

**Review by strantalis — APPROVED** [review]
