### PR TITLE
fix(core): align keycloak provisioning in one command

### LINKED ISSUE #1380: Deprecate `keycloak-from-config` command and unify in `keycloak` provisioning command for local development

### PR DESCRIPTION
**Pull request by jakedoublev**
Resolves #1380

### CODE REVIEW

File: service/cmd/provisionKeycloak.go [hunk 1]
```diff
@@ -2,70 +2,133 @@ package cmd
...
+		err := fixtures.SetupCustomKeycloak(ctx, kcParams, keycloakData)
+		if err != nil {
+			return err
+		}
+
+		return nil
+	},
+}
+
+var provisionKeycloakFromConfigCmd = &cobra.Command{
```
Comment (jrschumacher) [inline service/cmd/provisionKeycloak.go:69]:
```suggestion
var deprecatedProvisionKeycloakFromConfigCmd = &cobra.Command{
```

File: service/cmd/provisionKeycloak.go [hunk 2]
```diff
@@ -2,70 +2,133 @@ package cmd
...
 	provisionKeycloakCmd.Flags().StringP(provKcPasswordFlag, "p", "changeme", "Keycloak password")
-	provisionKeycloakCmd.Flags().StringP(provKcRealmFlag, "r", "opentdf", "OpenTDF Keycloak Realm name")
-	provisionKeycloakCmd.Flags().BoolP(provKcInsecure, "", false, "Ignore tls verification when connecting to keycloak. --insecure to disable.")
+	provisionKeycloakCmd.Flags().StringP(provKcFilenameFlag, "f", provKeycloakFilename, "Keycloak config file")
 
 	provisionCmd.AddCommand(provisionKeycloakCmd)
 
-	rootCmd.AddCommand(provisionKeycloakCmd)
+	// Deprecated command
+	provisionCmd.AddCommand(provisionKeycloakFromConfigCmd)
```
Comment (jrschumacher) [inline service/cmd/provisionKeycloak.go:133]:
```suggestion
	provisionCmd.AddCommand(deprecatedProvisionKeycloakFromConfigCmd)
```

**Review by jrschumacher — APPROVED** [review]

File: service/cmd/provisionKeycloak.go (hunk 1 above)
Comment (jakedoublev) [reply service/cmd/provisionKeycloak.go:69]: Will address in #1365
